@startuml
namespace notee {
    class Accidental << (S,Aquamarine) >> {
        + Value int

    }
    class Interval << (S,Aquamarine) >> {
        + Value int
        + Accidental Accidental

        + ToString() string

    }
    class Key << (S,Aquamarine) >> {
        + Value int

        + ToString() string

    }
    class Note << (S,Aquamarine) >> {
        + Key Key
        + Octave Octave

    }
    class Octave << (S,Aquamarine) >> {
        + Value int

    }
    class Pattern << (S,Aquamarine) >> {
        + Starts []Step
        + Lengths []Step
        + Translations []Interval
        + Scale Scale
        + Length Step

    }
    class Scale << (S,Aquamarine) >> {
        + Interval []Interval
        + Keys []Key

        + KeyToInterval(key Key) Interval
        + IntervalToKey(interval Interval) Key
        + ToString() string

    }
    class Score << (S,Aquamarine) >> {
        + Starts []Step
        + Lengths []Step
        + Notes []Note
        + Length Step

        + Extract(scale Scale) Pattern

    }
    class Step << (S,Aquamarine) >> {
        + Value int

    }
}


@enduml
